<?php

/**
 * @file
 * Provides NganLuong payment method for Drupal Commerce
 * 
 */
module_load_include('php', 'commerce_nganluong', 'includes/nganluong');

/**
 * Implements hook_menu().
 */
function commerce_nganluong_menu() {
  $items = array();

  // Define a path to verify payment from NganLuong.
  $items['commerce_nganluong/verify_payment/%commerce_payment_method'] = array(
    'page callback' => 'commerce_nganluong_verify_payment',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  // Define a path to display error message when payment error.
  $items['commerce_nganluong/payment_fail'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_nganluong_payment_fail'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}


/**
 * Menu callback: verify payment from NganLuong
 */
function commerce_nganluong_verify_payment($payment_method) {
  // Get transaction information
  $transaction_info = $_GET["transaction_info"];
  //Get order id
  $order_code = $_GET["order_code"];
  // load order by code
  $order = commerce_order_load($order_code);
  // Get total price
  $price = $_GET["price"];
  // Get remote payment transaction from NganLuong
  $payment_id = $_GET["payment_id"];
  //Get payment type from NganLuong
  $payment_type = $_GET["payment_type"];
  //get error message from NganLuong
  $error_text = $_GET["error_text"];
  //Get secure code
  $secure_code = $_GET["secure_code"];

  $nl = new NL_Checkout();
  $check = $nl->verifyPaymentUrl($transaction_info, $order_code, $price, $payment_id, $payment_type, $error_text, $secure_code);
  // if payment is success.
  if ($check) {
    // save payment transaction
    commerce_nganluong_save_payment_trasaction($order, $price, $payment_method, array($payment_id, $payment_type, $error_text, $secure_code));
    // go to next pane
    $return_url = url('checkout/' . $order->order_id . '/payment/return/' . $order->data['payment_redirect_key'], array('absolute' => TRUE));
    drupal_goto($return_url);
  } else { // payment fail
    // go to previous pane.
    $back_url = url('checkout/' . $order->order_id . '/payment/back/' . $order->data['payment_redirect_key'], array('absolute' => TRUE));
    drupal_goto($back_url);
  }
}

/**
 * Save payment transaction.
 *
 * @param object $order Object contain order info for payment.
 * @param float $price Total price in this payment.
 * @param array $payment_method Payment method info.
 * @param array $info Other info from NganLuong after we verify payment.
 */
function commerce_nganluong_save_payment_trasaction($order, $price, $payment_method, $info) {
  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
  $order_total = $order_wrapper->commerce_order_total->value();
  $transaction = commerce_payment_transaction_new('commerce_nganluong', $order->order_id);
  $transaction->instance_id = $payment_method['instance_id'];
  $transaction->remote_id = $info[0];
  $transaction->amount = commerce_currency_decimal_to_amount($price, $order_total['currency_code']);
  $transaction->currency_code = $order_total['currency_code'];
  $transaction->status = COMMERCE_PAYMENT_STATUS_SUCCESS;

  $transaction->message = 'Payment id: @payment_id; Payment type: @payment_type; Error text: @error_text; Secure code: @secure_code';
  $transaction->message_variables = array(
    '@payment_id' => $info[0],
    '@payment_type' => $info[1],
    '@error_text' => $info[2],
    '@secure_code' => $info[3],
  );
  commerce_payment_transaction_save($transaction);
}

/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_nganluong_commerce_payment_method_info() {
  $payment_methods = array();
  $payment_methods['commerce_nganluong'] = array(
    'title' => t('NganLuong payment'),
    'description' => t('Complete payment during checkout with NganLuong.'),
    'active' => TRUE,
    'short_title' => t('NganLuong'),
    'terminal' => FALSE,
    'offsite' => TRUE,
    'offsite_autoredirect' => TRUE,
  );

  return $payment_methods;
}

/**
 * Payment method callback: redirect form.
 */
function commerce_nganluong_redirect_form($form, &$form_state, $order, $payment_method) {
  // Return an error if the enabling action's settings haven't been configured.
  if (empty($payment_method['settings']['business'])) {
    drupal_set_message(t('NganLuong Payment is not configured for use. No receiver e-mail address has been specified.'), 'error');
    return array();
  }

  $url = commerce_nganluong_build_checkout_url($order, $payment_method['settings']);
  $form['#action'] = $url;

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Proceed to NganLuong'),
  );
  return $form;
}

/**
 * Build a checkout URL
 *
 * @return string The checkout URL for NganLuong payment.
 */
function commerce_nganluong_build_checkout_url($order, $settings) {
  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
  $receiver = $settings['business'];
  // Get return url: Nganluong will redirect to this URL after payment complete (can be fail or success)
  $return_url = url('commerce_nganluong/verify_payment/commerce_nganluong', array('absolute' => TRUE));
  // Get total order value
  $order_total = $order_wrapper->commerce_order_total->value();
  $price = commerce_currency_amount_to_decimal($order_total['amount'], $order_total['currency_code']);
  // Get order id (number)
  $order_code = $order->order_id;
  //Define transaction info
  $transaction_info = ""; // @todo
  // Define main object
  $nl = new NL_Checkout();

  // Call method buildCheckoutUrl() to build checkout url to send cho nganluong.vn
  $url = $nl->buildCheckoutUrl($return_url, $receiver, $transaction_info, $order_code, $price);
  return $url;
}

/**
 * Returns the default settings for the NganLuong payment method.
 */
function commerce_nganluong_default_settings() {
  return array(
    'business' => '',
  );
}

/**
 * Payment method callback: settings form.
 */
function commerce_nganluong_settings_form($settings = array()) {
  $form = array();
  // Merge default settings into the stored settings array.
  $settings = (array) $settings + commerce_nganluong_default_settings();
  $form['business'] = array(
    '#type' => 'textfield',
    '#title' => t('NganLuong receiver e-mail address'),
    '#description' => t('The primary e-mail address of the NganLuong account you want to use to receive payments.'),
    '#default_value' => $settings['business'],
    '#required' => TRUE,
  );

  return $form;
}

/**
 * Payment method callback: submit form.
 */
function commerce_nganluong_submit_form($payment_method, $pane_values, $checkout_pane, $order) {
  $form = array();
  // @todo: Add some helpful elements
  return $form;
}

/**
 * Payment method callback: submit form validation.
 */
function commerce_nganluong_submit_form_validate($payment_method, $pane_form, $pane_values, $order, $form_parents = array()) {
  // @todo: validate submit form
}

/**
 * Payment method callback: submit form submission.
 */
function commerce_nganluong_submit_form_submit($payment_method, $pane_form, $pane_values, $order, $charge) {
  $order->data['commerce_nganluong'] = $pane_values;
  // Generate a payment redirect key.
  $redirect_key = drupal_hash_base64(time());
  $order->data['payment_redirect_key'] = strtolower(urlencode($redirect_key));
  commerce_order_save($order);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add icon for NganLuong payment method in checkout form.
 */
function commerce_nganluong_form_commerce_checkout_form_alter(&$form, &$form_state) {
  // If this checkout form contains the payment method radios...
  if (!empty($form['commerce_payment']['payment_method']['#options'])) {
    // Loop over its options array looking for a PayPal WPS option.
    foreach ($form['commerce_payment']['payment_method']['#options'] as $key => &$value) {
      list($method_id, $rule_name) = explode('|', $key);
      if ($method_id == 'commerce_nganluong') {
        $logo = commerce_nganluong_logo();
        $value = t('!logo', array('!logo' => $logo));
        // Add the CSS.
        $form['commerce_payment']['payment_method']['#attached']['css'][] = drupal_get_path('module', 'commerce_nganluong') . '/css/commerce_nganluong.css';
        break;
      }
    }
  }
}

/**
 * Get logo for NganLuong payment.
 */
function commerce_nganluong_logo() {
  $variables = array(
    'path' => drupal_get_path('module', 'commerce_nganluong') . '/images/logo-nl.png',
    'title' => 'NganLuong Payment Method',
    'alt' => 'NganLuong Payment Method',
    'attributes' => array(
      'class' => array('commerce-nganluong-icon'),
    ),
  );
  return theme('image', $variables);
}

/**
 * Payment method callback: redirect_form_back
 *
 * Display error message if there is error with payment transaction.
 */
function commerce_nganluong_redirect_form_back($order, $payment_method) {
  drupal_set_message(t('There is an error with your payment. Please try again or contact administrator.'), 'error');
}
